### ISSUE TITLE
Please update this plugin to 1.19.3 

### ISSUE THREAD

**Issue by HonestWord** [NerdNu/SafeCrystals#1]

**Comment by totemo** [comment]
This still works fine. We are running it on Paper 1.19.3. Are you seeing a problem @HonestWord?

**Comment by HonestWord** [comment]
> This still works fine. We are running it on Paper 1.19.3. Are you seeing a problem @HonestWord?

i thought it does not work on 1.19.3 sorry
added it yesterday on 1.19.3 and it worked just fine, now people can use the Crystals for decoration. thanks ! 

crystals used by a member on the server: 
![image](https://user-images.githubusercontent.com/122177808/221346042-f38d3f01-0d39-42b6-abe9-0400e3a41989.png)
